version: '3.3'

services:

  srv:
    build:
      context: ../probe
      dockerfile: Dockerfile
    environment:
      GRPC_GO_LOG_VERBOSITY_LEVEL: 99
      GRPC_GO_LOG_SEVERITY_LEVEL: "info"
    env_file:
      - ./dev.env
    volumes:
      - ../probe:/appsrc
      - ../probe/cert:/cert
    command: tail -f /dev/null

  clnt:
    build:
      context: ./clnt
      dockerfile: Dockerfile
    env_file:
      - ./dev.env
    volumes:
      - ./clnt:/appsrc
    command: tail -f /dev/null