// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: gnmiprobe.proto

package gnmiprobe

import (
	gnmi "github.com/openconfig/gnmi/proto/gnmi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid     int64 `protobuf:"varint,1,opt,name=Cid,proto3" json:"Cid,omitempty"`
	Timeout int64 `protobuf:"varint,2,opt,name=Timeout,proto3" json:"Timeout,omitempty"` // second
	// Types that are assignable to Request:
	//	*ProbeRequest_Conn
	//	*ProbeRequest_Set
	//	*ProbeRequest_Get
	//	*ProbeRequest_Sub
	Request isProbeRequest_Request `protobuf_oneof:"request"`
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnmiprobe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gnmiprobe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_gnmiprobe_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeRequest) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *ProbeRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (m *ProbeRequest) GetRequest() isProbeRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *ProbeRequest) GetConn() *ProbeConn {
	if x, ok := x.GetRequest().(*ProbeRequest_Conn); ok {
		return x.Conn
	}
	return nil
}

func (x *ProbeRequest) GetSet() *gnmi.SetRequest {
	if x, ok := x.GetRequest().(*ProbeRequest_Set); ok {
		return x.Set
	}
	return nil
}

func (x *ProbeRequest) GetGet() *gnmi.GetRequest {
	if x, ok := x.GetRequest().(*ProbeRequest_Get); ok {
		return x.Get
	}
	return nil
}

func (x *ProbeRequest) GetSub() *gnmi.SubscribeRequest {
	if x, ok := x.GetRequest().(*ProbeRequest_Sub); ok {
		return x.Sub
	}
	return nil
}

type isProbeRequest_Request interface {
	isProbeRequest_Request()
}

type ProbeRequest_Conn struct {
	Conn *ProbeConn `protobuf:"bytes,5,opt,name=conn,proto3,oneof"`
}

type ProbeRequest_Set struct {
	Set *gnmi.SetRequest `protobuf:"bytes,6,opt,name=set,proto3,oneof"`
}

type ProbeRequest_Get struct {
	Get *gnmi.GetRequest `protobuf:"bytes,7,opt,name=get,proto3,oneof"`
}

type ProbeRequest_Sub struct {
	Sub *gnmi.SubscribeRequest `protobuf:"bytes,8,opt,name=sub,proto3,oneof"`
}

func (*ProbeRequest_Conn) isProbeRequest_Request() {}

func (*ProbeRequest_Set) isProbeRequest_Request() {}

func (*ProbeRequest_Get) isProbeRequest_Request() {}

func (*ProbeRequest_Sub) isProbeRequest_Request() {}

type ProbeConn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TLS  bool   `protobuf:"varint,1,opt,name=TLS,proto3" json:"TLS,omitempty"`
	Cer  string `protobuf:"bytes,2,opt,name=Cer,proto3" json:"Cer,omitempty"` // ca cert file name
	Host string `protobuf:"bytes,3,opt,name=Host,proto3" json:"Host,omitempty"`
	Port string `protobuf:"bytes,4,opt,name=Port,proto3" json:"Port,omitempty"`
	Usr  string `protobuf:"bytes,5,opt,name=Usr,proto3" json:"Usr,omitempty"`
	Pwd  string `protobuf:"bytes,6,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
}

func (x *ProbeConn) Reset() {
	*x = ProbeConn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnmiprobe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeConn) ProtoMessage() {}

func (x *ProbeConn) ProtoReflect() protoreflect.Message {
	mi := &file_gnmiprobe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeConn.ProtoReflect.Descriptor instead.
func (*ProbeConn) Descriptor() ([]byte, []int) {
	return file_gnmiprobe_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeConn) GetTLS() bool {
	if x != nil {
		return x.TLS
	}
	return false
}

func (x *ProbeConn) GetCer() string {
	if x != nil {
		return x.Cer
	}
	return ""
}

func (x *ProbeConn) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProbeConn) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ProbeConn) GetUsr() string {
	if x != nil {
		return x.Usr
	}
	return ""
}

func (x *ProbeConn) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type ProbeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid   int64                `protobuf:"varint,1,opt,name=Cid,proto3" json:"Cid,omitempty"`
	Error string               `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Resp  []*gnmi.Notification `protobuf:"bytes,3,rep,name=Resp,proto3" json:"Resp,omitempty"`
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnmiprobe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gnmiprobe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_gnmiprobe_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeResponse) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *ProbeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProbeResponse) GetResp() []*gnmi.Notification {
	if x != nil {
		return x.Resp
	}
	return nil
}

type SvrStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host    string `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Release string `protobuf:"bytes,2,opt,name=Release,proto3" json:"Release,omitempty"`
	Load    int64  `protobuf:"varint,3,opt,name=Load,proto3" json:"Load,omitempty"`
}

func (x *SvrStat) Reset() {
	*x = SvrStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnmiprobe_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvrStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvrStat) ProtoMessage() {}

func (x *SvrStat) ProtoReflect() protoreflect.Message {
	mi := &file_gnmiprobe_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvrStat.ProtoReflect.Descriptor instead.
func (*SvrStat) Descriptor() ([]byte, []int) {
	return file_gnmiprobe_proto_rawDescGZIP(), []int{3}
}

func (x *SvrStat) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SvrStat) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *SvrStat) GetLoad() int64 {
	if x != nil {
		return x.Load
	}
	return 0
}

type HealtzReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealtzReq) Reset() {
	*x = HealtzReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnmiprobe_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealtzReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealtzReq) ProtoMessage() {}

func (x *HealtzReq) ProtoReflect() protoreflect.Message {
	mi := &file_gnmiprobe_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealtzReq.ProtoReflect.Descriptor instead.
func (*HealtzReq) Descriptor() ([]byte, []int) {
	return file_gnmiprobe_proto_rawDescGZIP(), []int{4}
}

type ProbeBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ProbeBase) Reset() {
	*x = ProbeBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnmiprobe_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeBase) ProtoMessage() {}

func (x *ProbeBase) ProtoReflect() protoreflect.Message {
	mi := &file_gnmiprobe_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeBase.ProtoReflect.Descriptor instead.
func (*ProbeBase) Descriptor() ([]byte, []int) {
	return file_gnmiprobe_proto_rawDescGZIP(), []int{5}
}

func (x *ProbeBase) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type OprStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *OprStat) Reset() {
	*x = OprStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnmiprobe_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OprStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OprStat) ProtoMessage() {}

func (x *OprStat) ProtoReflect() protoreflect.Message {
	mi := &file_gnmiprobe_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OprStat.ProtoReflect.Descriptor instead.
func (*OprStat) Descriptor() ([]byte, []int) {
	return file_gnmiprobe_proto_rawDescGZIP(), []int{6}
}

func (x *OprStat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string           `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Request *gnmi.GetRequest `protobuf:"bytes,2,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnmiprobe_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gnmiprobe_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_gnmiprobe_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetRequest) GetRequest() *gnmi.GetRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type SetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string           `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Request *gnmi.SetRequest `protobuf:"bytes,2,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnmiprobe_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gnmiprobe_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_gnmiprobe_proto_rawDescGZIP(), []int{8}
}

func (x *SetRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *SetRequest) GetRequest() *gnmi.SetRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Request *gnmi.SubscribeRequest `protobuf:"bytes,2,opt,name=Request,proto3" json:"Request,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gnmiprobe_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gnmiprobe_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_gnmiprobe_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *SubscribeRequest) GetRequest() *gnmi.SubscribeRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

var File_gnmiprobe_proto protoreflect.FileDescriptor

var file_gnmiprobe_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x67, 0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x1a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x67, 0x6e, 0x6d, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6e, 0x6d, 0x69, 0x2f, 0x67, 0x6e, 0x6d, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe9,
	0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x43, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x43, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x63,
	0x6f, 0x6e, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6e, 0x6d, 0x69,
	0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x48,
	0x00, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x12, 0x24, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x24, 0x0a,
	0x03, 0x67, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x6e, 0x6d,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x03,
	0x67, 0x65, 0x74, 0x12, 0x2a, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x03, 0x73, 0x75, 0x62, 0x42,
	0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x7b, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x4c, 0x53, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x54, 0x4c, 0x53, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x73, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x55, 0x73, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x77, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x50, 0x77, 0x64, 0x22, 0x5f, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x43, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x26, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x04, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4b, 0x0a, 0x07, 0x53, 0x76, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x4c, 0x6f, 0x61, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x7a, 0x52,
	0x65, 0x71, 0x22, 0x1b, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x21, 0x0a, 0x07, 0x4f, 0x70, 0x72, 0x53, 0x74, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x48, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x2a, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x0a,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x6e,
	0x6d, 0x69, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x30, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6e,
	0x6d, 0x69, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0xe6, 0x03, 0x0a,
	0x05, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x7a,
	0x12, 0x14, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x7a, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f,
	0x62, 0x65, 0x2e, 0x53, 0x76, 0x72, 0x53, 0x74, 0x61, 0x74, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x12, 0x17, 0x2e, 0x67,
	0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f, 0x62,
	0x65, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x37, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x12, 0x14, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x50, 0x72, 0x6f,
	0x62, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x1a, 0x14, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f,
	0x62, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x42, 0x61, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38,
	0x0a, 0x0a, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x14, 0x2e, 0x67,
	0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x42, 0x61,
	0x73, 0x65, 0x1a, 0x12, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x4f,
	0x70, 0x72, 0x53, 0x74, 0x61, 0x74, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0a, 0x43, 0x61, 0x70, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x14, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f,
	0x62, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x42, 0x61, 0x73, 0x65, 0x1a, 0x18, 0x2e, 0x67,
	0x6e, 0x6d, 0x69, 0x2e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12,
	0x15, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x03, 0x53,
	0x65, 0x74, 0x12, 0x15, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x67, 0x6e, 0x6d, 0x69,
	0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x1b, 0x2e, 0x67, 0x6e,
	0x6d, 0x69, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x2e,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x62, 0x61,
	0x6e, 0x64, 0x2f, 0x67, 0x6e, 0x6d, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x6e, 0x6d, 0x69,
	0x70, 0x72, 0x6f, 0x62, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gnmiprobe_proto_rawDescOnce sync.Once
	file_gnmiprobe_proto_rawDescData = file_gnmiprobe_proto_rawDesc
)

func file_gnmiprobe_proto_rawDescGZIP() []byte {
	file_gnmiprobe_proto_rawDescOnce.Do(func() {
		file_gnmiprobe_proto_rawDescData = protoimpl.X.CompressGZIP(file_gnmiprobe_proto_rawDescData)
	})
	return file_gnmiprobe_proto_rawDescData
}

var file_gnmiprobe_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gnmiprobe_proto_goTypes = []interface{}{
	(*ProbeRequest)(nil),            // 0: gnmiprobe.ProbeRequest
	(*ProbeConn)(nil),               // 1: gnmiprobe.ProbeConn
	(*ProbeResponse)(nil),           // 2: gnmiprobe.ProbeResponse
	(*SvrStat)(nil),                 // 3: gnmiprobe.SvrStat
	(*HealtzReq)(nil),               // 4: gnmiprobe.HealtzReq
	(*ProbeBase)(nil),               // 5: gnmiprobe.ProbeBase
	(*OprStat)(nil),                 // 6: gnmiprobe.OprStat
	(*GetRequest)(nil),              // 7: gnmiprobe.GetRequest
	(*SetRequest)(nil),              // 8: gnmiprobe.SetRequest
	(*SubscribeRequest)(nil),        // 9: gnmiprobe.SubscribeRequest
	(*gnmi.SetRequest)(nil),         // 10: gnmi.SetRequest
	(*gnmi.GetRequest)(nil),         // 11: gnmi.GetRequest
	(*gnmi.SubscribeRequest)(nil),   // 12: gnmi.SubscribeRequest
	(*gnmi.Notification)(nil),       // 13: gnmi.Notification
	(*gnmi.CapabilityResponse)(nil), // 14: gnmi.CapabilityResponse
	(*gnmi.GetResponse)(nil),        // 15: gnmi.GetResponse
	(*gnmi.SetResponse)(nil),        // 16: gnmi.SetResponse
	(*gnmi.SubscribeResponse)(nil),  // 17: gnmi.SubscribeResponse
}
var file_gnmiprobe_proto_depIdxs = []int32{
	1,  // 0: gnmiprobe.ProbeRequest.conn:type_name -> gnmiprobe.ProbeConn
	10, // 1: gnmiprobe.ProbeRequest.set:type_name -> gnmi.SetRequest
	11, // 2: gnmiprobe.ProbeRequest.get:type_name -> gnmi.GetRequest
	12, // 3: gnmiprobe.ProbeRequest.sub:type_name -> gnmi.SubscribeRequest
	13, // 4: gnmiprobe.ProbeResponse.Resp:type_name -> gnmi.Notification
	11, // 5: gnmiprobe.GetRequest.Request:type_name -> gnmi.GetRequest
	10, // 6: gnmiprobe.SetRequest.Request:type_name -> gnmi.SetRequest
	12, // 7: gnmiprobe.SubscribeRequest.Request:type_name -> gnmi.SubscribeRequest
	4,  // 8: gnmiprobe.Probe.Healtz:input_type -> gnmiprobe.HealtzReq
	0,  // 9: gnmiprobe.Probe.ConnectProbe:input_type -> gnmiprobe.ProbeRequest
	1,  // 10: gnmiprobe.Probe.Connect:input_type -> gnmiprobe.ProbeConn
	5,  // 11: gnmiprobe.Probe.Disconnect:input_type -> gnmiprobe.ProbeBase
	5,  // 12: gnmiprobe.Probe.Capability:input_type -> gnmiprobe.ProbeBase
	7,  // 13: gnmiprobe.Probe.Get:input_type -> gnmiprobe.GetRequest
	8,  // 14: gnmiprobe.Probe.Set:input_type -> gnmiprobe.SetRequest
	9,  // 15: gnmiprobe.Probe.Subscribe:input_type -> gnmiprobe.SubscribeRequest
	3,  // 16: gnmiprobe.Probe.Healtz:output_type -> gnmiprobe.SvrStat
	2,  // 17: gnmiprobe.Probe.ConnectProbe:output_type -> gnmiprobe.ProbeResponse
	5,  // 18: gnmiprobe.Probe.Connect:output_type -> gnmiprobe.ProbeBase
	6,  // 19: gnmiprobe.Probe.Disconnect:output_type -> gnmiprobe.OprStat
	14, // 20: gnmiprobe.Probe.Capability:output_type -> gnmi.CapabilityResponse
	15, // 21: gnmiprobe.Probe.Get:output_type -> gnmi.GetResponse
	16, // 22: gnmiprobe.Probe.Set:output_type -> gnmi.SetResponse
	17, // 23: gnmiprobe.Probe.Subscribe:output_type -> gnmi.SubscribeResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_gnmiprobe_proto_init() }
func file_gnmiprobe_proto_init() {
	if File_gnmiprobe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gnmiprobe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnmiprobe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeConn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnmiprobe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnmiprobe_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvrStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnmiprobe_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealtzReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnmiprobe_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnmiprobe_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OprStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnmiprobe_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnmiprobe_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gnmiprobe_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_gnmiprobe_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ProbeRequest_Conn)(nil),
		(*ProbeRequest_Set)(nil),
		(*ProbeRequest_Get)(nil),
		(*ProbeRequest_Sub)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gnmiprobe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gnmiprobe_proto_goTypes,
		DependencyIndexes: file_gnmiprobe_proto_depIdxs,
		MessageInfos:      file_gnmiprobe_proto_msgTypes,
	}.Build()
	File_gnmiprobe_proto = out.File
	file_gnmiprobe_proto_rawDesc = nil
	file_gnmiprobe_proto_goTypes = nil
	file_gnmiprobe_proto_depIdxs = nil
}
